CREATE TABLE clientes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(80) NOT NULL,
    apellido VARCHAR(80) NOT NULL,
    documento VARCHAR(30) NOT NULL UNIQUE,
    email VARCHAR(160) NOT NULL UNIQUE,
    telefono VARCHAR(30) NOT NULL,
    fecha_registro TIMESTAMP NOT NULL
);

CREATE TABLE vehiculos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    placa VARCHAR(12) NOT NULL UNIQUE,
    marca VARCHAR(60) NOT NULL,
    modelo VARCHAR(80) NOT NULL,
    anio INTEGER NOT NULL CHECK (anio BETWEEN 1900 AND 2100),
    precio_cop NUMERIC(15, 2) NOT NULL CHECK (precio_cop > 0),
    estado VARCHAR(24) NOT NULL CHECK (estado IN ('DISPONIBLE', 'VENDIDO', 'EN_MANTENIMIENTO')),
    version BIGINT NOT NULL
);

CREATE TABLE ventas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id BIGINT NOT NULL REFERENCES clientes(id),
    vehiculo_id BIGINT NOT NULL UNIQUE REFERENCES vehiculos(id),
    fecha_venta TIMESTAMP NOT NULL,
    descuento_aplicado NUMERIC(15, 2) NOT NULL CHECK (descuento_aplicado >= 0),
    monto_total NUMERIC(15, 2) NOT NULL CHECK (monto_total >= 0)
);

CREATE TABLE mantenimientos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehiculo_id BIGINT NOT NULL REFERENCES vehiculos(id),
    fecha_mantenimiento DATE NOT NULL,
    descripcion VARCHAR(500) NOT NULL,
    costo NUMERIC(15, 2) NOT NULL CHECK (costo >= 0)
);

CREATE INDEX idx_vehiculos_marca ON vehiculos(marca);
CREATE INDEX idx_vehiculos_estado ON vehiculos(estado);
CREATE INDEX idx_ventas_cliente ON ventas(cliente_id);
CREATE INDEX idx_mantenimientos_vehiculo ON mantenimientos(vehiculo_id);
